src/Entity/Account.php
<?php

namespace Kibuzn\Entity;

use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Kibuzn\Repository\AccountRepository;

#[ORM\Entity(repositoryClass: AccountRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Account
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    private ?string $name = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'accounts')]
    private Collection $users;

    #[ORM\Column]
    private ?DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?DateTimeImmutable $updated_at = null;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $deleted_at = null;

    /**
     * @var Collection<int, Transaction>
     */
    #[ORM\OneToMany(targetEntity: Transaction::class, mappedBy: 'account')]
    private Collection $transactions;

    /**
     * @var Collection<int, RecurringTransaction>
     */
    #[ORM\OneToMany(targetEntity: RecurringTransaction::class, mappedBy: 'account')]
    private Collection $recurringTransactions;

    #[ORM\ManyToOne(targetEntity: Bank::class, fetch: 'EAGER')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Bank $bank = null;

    #[ORM\Column]
    private ?bool $main = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->transactions = new ArrayCollection();
        $this->recurringTransactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        $this->users->removeElement($user);

        return $this;
    }


    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->created_at;
    }

    #[ORM\PrePersist]
    public function setCreatedAt(): void
    {
        $now = new DateTimeImmutable();
        $this->created_at = $now;
        $this->updated_at = $now;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updated_at;
    }

    #[ORM\PreUpdate]
    public function setUpdatedAt(): void
    {
        $this->updated_at = new DateTimeImmutable();
    }

    public function getDeletedAt(): ?DateTimeImmutable
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?DateTimeImmutable $deleted_at): static
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * @return Collection<int, Transaction>
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): static
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions->add($transaction);
            $transaction->setAccount($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): static
    {
        if ($this->transactions->removeElement($transaction)) {
            // set the owning side to null (unless already changed)
            if ($transaction->getAccount() === $this) {
                $transaction->setAccount(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, RecurringTransaction>
     */
    public function getRecurringTransactions(): Collection
    {
        return $this->recurringTransactions;
    }

    public function addRecurringTransaction(RecurringTransaction $recurringTransaction): static
    {
        if (!$this->recurringTransactions->contains($recurringTransaction)) {
            $this->recurringTransactions->add($recurringTransaction);
            $recurringTransaction->setAccount($this);
        }

        return $this;
    }

    public function removeRecurringTransaction(RecurringTransaction $recurringTransaction): static
    {
        if ($this->recurringTransactions->removeElement($recurringTransaction)) {
            // set the owning side to null (unless already changed)
            if ($recurringTransaction->getAccount() === $this) {
                $recurringTransaction->setAccount(null);
            }
        }

        return $this;
    }

    public function getBank(): ?Bank
    {
        return $this->bank;
    }

    public function setBank(?Bank $bank): static
    {
        $this->bank = $bank;

        return $this;
    }

    public function isMain(): ?bool
    {
        return $this->main;
    }

    public function setMain(bool $main): static
    {
        $this->main = $main;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace Kibuzn\Entity;

use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Kibuzn\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    /**
     * @var Collection<int, Account>
     */
    #[ORM\ManyToMany(targetEntity: Account::class, mappedBy: 'users')]
    private Collection $accounts;

    #[ORM\Column(length: 50)]
    private ?string $firstname = null;

    #[ORM\Column(length: 50)]
    private ?string $lastname = null;

    #[ORM\Column(length: 50)]
    private ?string $timezone = null;

    #[ORM\Column]
    private ?DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?DateTimeImmutable $updated_at = null;

    #[ORM\Column(nullable: true)] // A listener will be implemented to update this field
    private ?DateTimeImmutable $last_login_at = null;

    #[ORM\Column(nullable: true)] // Nullable until a listener is implemented
    private ?DateTimeImmutable $last_action_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $verified_at = null;

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Account>
     */
    public function getAccounts(): Collection
    {
        return $this->accounts;
    }

    public function addAccount(Account $account): static
    {
        if (!$this->accounts->contains($account)) {
            $this->accounts->add($account);
            $account->addUser($this);
        }

        return $this;
    }

    public function removeAccount(Account $account): static
    {
        if ($this->accounts->removeElement($account)) {
            $account->removeUser($this);
        }

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getTimezone(): ?string
    {
        return $this->timezone;
    }

    public function setTimezone(string $timezone): static
    {
        $this->timezone = $timezone;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->created_at;
    }

    #[ORM\PrePersist]
    public function setCreatedAt(): void
    {
        $now = new DateTimeImmutable();
        $this->created_at = $now;
        $this->updated_at = $now;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updated_at;
    }

    #[ORM\PreUpdate]
    public function setUpdatedAt(PreUpdateEventArgs $event): void
    {
        // Check if the 'last_login_at' field is the only one updated
        if (
            ($event->hasChangedField('last_login_at') || $event->hasChangedField('last_action_at'))
            && count($event->getEntityChangeSet()) === 1
        ) {
            // Only the last_login_at or last_action_at field was updated
            return;
        }

        // Update the updated_at field if other fields were changed
        $this->updated_at = new DateTimeImmutable();
    }

    public function getLastLoginAt(): ?DateTimeImmutable
    {
        return $this->last_login_at;
    }

    public function setLastLoginAt(DateTimeImmutable $last_login_at): static
    {
        $this->last_login_at = $last_login_at;

        return $this;
    }

    public function getLastActionAt(): ?DateTimeImmutable
    {
        return $this->last_action_at;
    }

    public function setLastActionAt(DateTimeImmutable $last_action_at): static
    {
        $this->last_action_at = $last_action_at;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getVerifiedAt(): ?\DateTimeImmutable
    {
        return $this->verified_at;
    }

    public function setVerifiedAt(?\DateTimeImmutable $verified_at): static
    {
        $this->verified_at = $verified_at;

        return $this;
    }
}

src/Controller/App/RecurringTransactionController.php
<?php

namespace Kibuzn\Controller\App;

use Doctrine\ORM\EntityManagerInterface;
use Kibuzn\Entity\RecurringTransaction;
use Kibuzn\Form\RecurringTransactionType;
use Kibuzn\Repository\RecurringTransactionRepository;
use Kibuzn\Service\AccountService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/recurring-transaction')]
final class RecurringTransactionController extends AbstractController
{
    #[Route(name: 'app_recurring_transaction_index', methods: ['GET'])]
    public function index(RecurringTransactionRepository $recurringTransactionRepository, AccountService $accountService): Response
    {
        return $this->render('recurring_transaction/index.html.twig', [
            'recurring_transactions' => $recurringTransactionRepository->findBy(['account' => $accountService->getSelectedAccount()]),
        ]);
    }

    #[Route('/new', name: 'app_recurring_transaction_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, AccountService $accountService): Response
    {
        $recurringTransaction = new RecurringTransaction();
        $form = $this->createForm(RecurringTransactionType::class, $recurringTransaction);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recurringTransaction->setAccount($accountService->getSelectedAccount());
            $entityManager->persist($recurringTransaction);
            $entityManager->flush();
            return $this->redirectToRoute('app_recurring_transaction_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('recurring_transaction/new.html.twig', [
            'recurring_transaction' => $recurringTransaction,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recurring_transaction_show', methods: ['GET'])]
    public function show(RecurringTransaction $recurringTransaction): Response
    {
        return $this->render('recurring_transaction/show.html.twig', [
            'recurring_transaction' => $recurringTransaction,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_recurring_transaction_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, RecurringTransaction $recurringTransaction, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RecurringTransactionType::class, $recurringTransaction);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            return $this->redirectToRoute('app_recurring_transaction_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('recurring_transaction/edit.html.twig', [
            'recurring_transaction' => $recurringTransaction,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recurring_transaction_delete', methods: ['POST'])]
    public function delete(Request $request, RecurringTransaction $recurringTransaction, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recurringTransaction->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($recurringTransaction);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_recurring_transaction_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/recurring_transaction/_delete_form.html.twig
<form method="post" action="{{ path('app_recurring_transaction_delete', {'id': recurring_transaction.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recurring_transaction.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recurring_transaction/_form.html.twig
{{ form_start(form, { attr: { 'data-controller': 'recurring-transaction-duration', 'data-action': 'change->recurring-transaction-duration#durationChange' } }) }}

<div class="mt-6 space-y-12">
    {{ form_widget(form) }}
    
    <div class="mt-6 flex items-center justify-end gap-x-6">
        <a href="{{ path('app_recurring_transaction_index') }}" class="text-sm font-semibold leading-6 text-gray-900">Cancel</a>
        <button type="submit" class="btn rounded-md bg-violet-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-violet-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-600">
            {{ button_label|default('Save') }}
        </button>
    </div>
</div>

{{ form_end(form) }}

templates/recurring_transaction/edit.html.twig
{% extends 'layout.html.twig' %}

    {% block title %}Edit Recurring Transaction
    {% endblock %}
    
    {% block content %}
    
    
        <div class="sm:flex sm:items-center">
    
            <div class="sm:flex-auto">
                {% include '_elements/_back_button.html.twig' with {'to': 'Recurring Transactions', 'route': path('app_recurring_transaction_index')} %}
                <h1 class="text-base font-semibold leading-6 text-gray-900">Edit Recurring Transaction</h1>
            </div>
    
        </div>
    
        {{ include('recurring_transaction/_form.html.twig') }}
    
    {# {{ include('recurring_transaction/_delete_form.html.twig') }} #}
    
    {% endblock %}

templates/recurring_transaction/new.html.twig
{% extends 'layout.html.twig' %}

    {% block title %}New Recurring Transaction
    {% endblock %}
    
    {% block content %}
    
            <div class="sm:flex sm:items-center">
    
                <div class="sm:flex-auto">
                    {% include '_elements/_back_button.html.twig' with {'to': 'Recurring Transactions', 'route': path('app_recurring_transaction_index')} %}
                    <h1 class="text-base font-semibold leading-6 text-gray-900">Create a new Recurring Transaction</h1>
                    <p class="mt-2 text-sm text-gray-700">Please fill in the form below to create a new recurring transaction.
                    </p>
                </div>
    
            </div>
    
            {% include('recurring_transaction/fragments/_form_nav.html.twig') with {
                'one_time_route': 'app_transaction_new',
                'recurring_route': 'app_recurring_transaction_new'
            } %}
    
            {% include('recurring_transaction/_form.html.twig') %}
    
    {% endblock %}

templates/recurring_transaction/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}RecurringTransaction{% endblock %}

{% block body %}
    <h1>RecurringTransaction</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ recurring_transaction.id }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ recurring_transaction.amount|number_format(2, ',', ' ') }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ recurring_transaction.description }}</td>
            </tr>
            <tr>
                <th>Recurrence_interval</th>
                <td>{{ recurring_transaction.recurrenceInterval }}</td>
            </tr>
            <tr>
                <th>Recurrence_value</th>
                <td>{{ recurring_transaction.recurrenceValue }}</td>
            </tr>
            <tr>
                <th>Recurrence_end_date</th>
                <td>{{ recurring_transaction.recurrenceEndDate ? recurring_transaction.recurrenceEndDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ recurring_transaction.createdAt ? recurring_transaction.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ recurring_transaction.updatedAt ? recurring_transaction.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Deleted_at</th>
                <td>{{ recurring_transaction.deletedAt ? recurring_transaction.deletedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_recurring_transaction_index') }}">back to list</a>

    <a href="{{ path('app_recurring_transaction_edit', {'id': recurring_transaction.id}) }}">edit</a>

    {{ include('recurring_transaction/_delete_form.html.twig') }}
{% endblock %}