src/Entity/RecurringTransaction.php
<?php

namespace Kibuzn\Entity;

use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Kibuzn\Repository\RecurringTransactionRepository;

#[ORM\Entity(repositoryClass: RecurringTransactionRepository::class)]
#[ORM\HasLifecycleCallbacks]
class RecurringTransaction
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $amount = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?DateTimeImmutable $updated_at = null;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $deleted_at = null;

    /**
     * @var Collection<int, Transaction>
     */
    #[ORM\OneToMany(targetEntity: Transaction::class, mappedBy: 'recurring_transaction_id')]
    private Collection $transactions;

    #[ORM\ManyToOne(inversedBy: 'recurringTransactions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Account $account = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?DateTimeInterface $start_date = null;

    #[ORM\Column(nullable: true)]
    private ?int $iterations = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?DateTimeInterface $end_date = null;

    #[ORM\Column(length: 20)]
    private ?string $interval_type = null;

    #[ORM\Column]
    private ?int $interval_value = null;

    #[ORM\ManyToOne(inversedBy: 'recurringTransactions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?OperationType $Type = null;

    public function __construct()
    {
        $this->transactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->created_at;
    }

    #[ORM\PrePersist]
    public function setCreatedAt(): void
    {
        $now = new DateTimeImmutable();
        $this->created_at = $now;
        $this->updated_at = $now;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updated_at;
    }

    #[ORM\PreUpdate]
    public function setUpdatedAt(): void
    {
        $this->updated_at = new DateTimeImmutable();
    }

    public function getDeletedAt(): ?DateTimeImmutable
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?DateTimeImmutable $deleted_at): static
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * @return Collection<int, Transaction>
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): static
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions->add($transaction);
            $transaction->setRecurringTransaction($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): static
    {
        if ($this->transactions->removeElement($transaction)) {
            // set the owning side to null (unless already changed)
            if ($transaction->getRecurringTransaction() === $this) {
                $transaction->setRecurringTransaction(null);
            }
        }

        return $this;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): static
    {
        $this->account = $account;

        return $this;
    }

    public function getStartDate(): ?DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getIterations(): ?int
    {
        return $this->iterations;
    }

    public function setIterations(?int $iterations): static
    {
        $this->iterations = $iterations;

        return $this;
    }

    public function getEndDate(): ?DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getIntervalType(): ?string
    {
        return $this->interval_type;
    }

    public function setIntervalType(string $interval_type): static
    {
        $this->interval_type = $interval_type;

        return $this;
    }

    public function getIntervalValue(): ?int
    {
        return $this->interval_value;
    }

    public function setIntervalValue(int $interval_value): static
    {
        $this->interval_value = $interval_value;

        return $this;
    }

    public function getType(): ?OperationType
    {
        return $this->Type;
    }

    public function setType(?OperationType $Type): static
    {
        $this->Type = $Type;

        return $this;
    }
}

src/Form/RecurringTransactionType.php
<?php

namespace Kibuzn\Form;

use Kibuzn\Entity\OperationType;
use Kibuzn\Entity\RecurringTransaction;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Choice;

class RecurringTransactionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type', EntityType::class, [
                'class' => OperationType::class,
                'choice_label' => 'name',
            ])
            ->add('description')
            ->add('amount')
            ->add('start_date', null, [
                'widget' => 'single_text',
            ])
            ->add('duration', ChoiceType::class, [
                'mapped' => false,
                'choices' => [
                    'permanent'                 => 1,
                    'with end date'             => 2,
                    'with number of iterations' => 3,
                ],
                'attr' => [
                    'data-recurring-transaction-duration-target' => 'duration',
                ],
            ])

            ->add('iterations', null, [
                'required' => false,
                'attr' => [
                    'data-recurring-transaction-duration-target' => 'iterations',
                    'min' => 2,
                    'max' => 1000,
                ],
            ])

            ->add('end_date', null, [
                'widget' => 'single_text',
                'required' => false,
                'attr' => [
                    'data-recurring-transaction-duration-target' => 'endDate',
                ],
            ])

            ->add('interval_type', ChoiceType::class, [
                'choices' => [
                    'day'   => 'day',
                    'week'  => 'week',
                    'month' => 'month',
                    'year'  => 'year',
                ],
                'constraints' => [
                    new Choice([
                        'choices' => ['day', 'week', 'month', 'year'],
                    ]),
                ],
            ])
            ->add('interval_value', null, [
                'attr' => [
                    'value' => 1,
                    'min' => 1,
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => RecurringTransaction::class,
        ]);
    }
}

src/Controller/App/RecurringTransactionController.php
<?php

namespace Kibuzn\Controller\App;

use Doctrine\ORM\EntityManagerInterface;
use Kibuzn\Entity\RecurringTransaction;
use Kibuzn\Form\RecurringTransactionType;
use Kibuzn\Repository\RecurringTransactionRepository;
use Kibuzn\Service\AccountService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/recurring-transaction')]
final class RecurringTransactionController extends AbstractController
{
    #[Route(name: 'app_recurring_transaction_index', methods: ['GET'])]
    public function index(RecurringTransactionRepository $recurringTransactionRepository, AccountService $accountService): Response
    {
        return $this->render('recurring_transaction/index.html.twig', [
            'recurring_transactions' => $recurringTransactionRepository->findBy(['account' => $accountService->getSelectedAccount()]),
        ]);
    }

    #[Route('/new', name: 'app_recurring_transaction_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, AccountService $accountService): Response
    {
        $recurringTransaction = new RecurringTransaction();
        $form = $this->createForm(RecurringTransactionType::class, $recurringTransaction);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recurringTransaction->setAccount($accountService->getSelectedAccount());
            $entityManager->persist($recurringTransaction);
            $entityManager->flush();
            return $this->redirectToRoute('app_recurring_transaction_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('recurring_transaction/new.html.twig', [
            'recurring_transaction' => $recurringTransaction,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recurring_transaction_show', methods: ['GET'])]
    public function show(RecurringTransaction $recurringTransaction): Response
    {
        return $this->render('recurring_transaction/show.html.twig', [
            'recurring_transaction' => $recurringTransaction,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_recurring_transaction_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, RecurringTransaction $recurringTransaction, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RecurringTransactionType::class, $recurringTransaction);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            return $this->redirectToRoute('app_recurring_transaction_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('recurring_transaction/edit.html.twig', [
            'recurring_transaction' => $recurringTransaction,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recurring_transaction_delete', methods: ['POST'])]
    public function delete(Request $request, RecurringTransaction $recurringTransaction, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recurringTransaction->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($recurringTransaction);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_recurring_transaction_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/recurring_transaction/fragments/_form_nav.html.twig
<div class="mt-6">
  <div class="sm:hidden">
    <label for="tabs" class="sr-only">Select a tab</label>
    <!-- Use an "onChange" listener to redirect the user to the selected tab URL. -->
    <select id="tabs" name="tabs" class="block w-full rounded-md border-gray-300 focus:border-violet-500 focus:ring-violet-500">
      <option selected>One-time</option>
      <option>Recurring</option>
    </select>
  </div>
  <div class="hidden sm:block">
    <nav class="isolate flex divide-x divide-gray-200 rounded-lg shadow" aria-label="Tabs">
      <!-- Current: "text-gray-900", Default: "text-gray-500 hover:text-gray-700" -->
      <a href="{{ path('app_transaction_new') }}" class="group relative min-w-0 flex-1 overflow-hidden rounded-r-lg bg-gray-100 px-4 py-4 text-center text-sm font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-700 focus:z-10">
        <span>One-time</span>
        <span aria-hidden="true" class="absolute inset-x-0 bottom-0 h-0.5 bg-transparent"></span>
      </a>
      <a href="{{ path('app_recurring_transaction_new') }}" class="group relative min-w-0 flex-1 overflow-hidden rounded-l-lg bg-gray-100 px-4 py-4 text-center text-sm font-medium text-gray-900 hover:bg-gray-50 focus:z-10" aria-current="page">
        <span>Recurring</span>
        <span aria-hidden="true" class="absolute inset-x-0 bottom-0 h-0.5 bg-violet-500"></span>
      </a>
    </nav>
  </div>
</div>

templates/recurring_transaction/fragments/_index_row.html.twig
<tr>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
        {{ recurring_transaction.description }}
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
        {{ recurring_transaction.amount|number_format(2, ',', ' ') }}
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
        {{ recurring_transaction.startDate|date('Y-m-d') }}
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
        <!-- put something for permanent -->
        {% if recurring_transaction.endDate %}
            {{ recurring_transaction.endDate|date('Y-m-d') }}
        {% elseif recurring_transaction.iterations %}
            {{ recurring_transaction.iterations }} iterations
        {% else %}
            N/A
        {% endif %}
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
        Every {{ recurring_transaction.intervalValue }} {{ recurring_transaction.intervalType }}
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
        {% if recurring_transaction.endDate and recurring_transaction.endDate < date() %}
            <span class="text-red-500">Ended</span>
        {% else %}
            <span class="text-green-500">Active</span>
        {% endif %}
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
        <a href="{{ path('app_recurring_transaction_show', {'id': recurring_transaction.id}) }}" class="text-indigo-600 hover:text-indigo-900">Show</a>
        <a href="{{ path('app_recurring_transaction_edit', {'id': recurring_transaction.id}) }}" class="ml-2 text-indigo-600 hover:text-indigo-900">Edit</a>
    </td>
</tr>